version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: bash -c 'sleep 3 && npm install --save sequelize-cli && npm start'
    volumes:
      - ./app:/app