version: "3.8"
services:
  app:
    image: amarynets/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    environment: 
      DATABASE_NAME: "${DATABASE_NAME:-postgres}"
      DATABASE_USERNAME: "${DATABASE_USERNAME:-postgres}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password}"