version: "3.8"
services:
  app:
    image: amarynets/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"